const testData = [
  {
    "__EMPTY": 1,
    "TC ID": "Pos_Fun_001",
    "Test Case Name": "Verify translation of compound daily conversation",
    "Input Type Length": "M",
    "Input": "mama adha uni yanna inne. oyaath ennakoo apith ekka lectures yanna. ",
    "Expected Output": "මම අද uni යන්න ඉන්නේ. ඔයාත් එන්නකෝ අපිත් එක්ක lectures යන්න. ",
    "Actual Output": "මම අද uni යන්න ඉන්නේ. ඔයාත් එන්නකෝ අපිත් එක්ක lectures යන්න. ",
    "Status": "PASS",
    "What is covered by the test": "Daily language usage\r\nCompound sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 2,
    "TC ID": "Pos_Fun_002",
    "Test Case Name": "Verify translation of positive sentence form",
    "Input Type Length": "M",
    "Input": "mee paara viBhaagaya oyaata hoDHAtama karanna puluvan",
    "Expected Output": "මේ පාර විභාගය ඔයාට හොඳටම කරන්න පුලුවන්",
    "Actual Output": "මේ පාර විභාගය ඔයාට හොඳටම කරන්න පුලුවන්",
    "Status": "PASS",
    "What is covered by the test": "Response\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 3,
    "TC ID": "Pos_Fun_003",
    "Test Case Name": "Verify  translation of negative sentence form",
    "Input Type Length": "M",
    "Input": "oyaa kaalaya apathee yaevvoth kavadhaavath viBhaagaya samath venna baeri venavaa",
    "Expected Output": "ඔයා කාලය අපතේ යැව්වොත් කවදාවත් විභාගය සමත් වෙන්න බැරි වෙනවා",
    "Actual Output": "ඔයා කාලය අපතේ යැව්වොත් කවදාවත් විභාගය සමත් වෙන්න බැරි වෙනවා",
    "Status": "PASS",
    "What is covered by the test": "Daily language usage\r\nNegation (negative form)\r\nM (31-299 characters)\r\nAccuracy Validation\r\n"
  },
  {
    "__EMPTY": 4,
    "TC ID": "Pos_Fun_004",
    "Test Case Name": "Verify  translation of informal phrasing",
    "Input Type Length": "M",
    "Input": "anee mee! oyaa ehema kivvaa kiyalaa mata eeka karanna baee.",
    "Expected Output": "අනේ මේ! ඔයා එහෙම කිව්වා කියලා මට ඒක කරන්න බෑ.",
    "Actual Output": "අනේ මේ! ඔයා එහෙම කිව්වා කියලා මට ඒක කරන්න බෑ.",
    "Status": "PASS",
    "What is covered by the test": "Slang / informal language\r\nPronoun variation \r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 5,
    "TC ID": "Pos_Fun_005",
    "Test Case Name": "Verify  translation of simple frequently used day-to-day expressions",
    "Input Type Length": "S",
    "Input": "mama adha udhenma avadhi vunaa",
    "Expected Output": "මම අද උදෙන්ම අවදි වුනා",
    "Actual Output": "මම අද උදෙන්ම අවදි වුනා",
    "Status": "PASS",
    "What is covered by the test": "Daily language usage\r\nSimple sentence\r\nS (≤30 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 6,
    "TC ID": "Pos_Fun_006",
    "Test Case Name": "Verify translation of frequent collocations ",
    "Input Type Length": "S",
    "Input": "eeka harima lassanayi nee",
    "Expected Output": "ඒක හරිම ලස්සනයි නේ",
    "Actual Output": "ඒක හරිම ලස්සනයි නේ",
    "Status": "PASS",
    "What is covered by the test": "Word combination / phrase pattern\r\nSimple sentence\r\nS (≤30 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 7,
    "TC ID": "Pos_Fun_007",
    "Test Case Name": "Verify translation of repeated word expressions used for emphasis",
    "Input Type Length": "M",
    "Input": "vaessa himin himin mee paeththatath enavaa vagee nee",
    "Expected Output": "වැස්ස හිමින් හිමින් මේ පැත්තටත් එනවා වගේ නේ",
    "Actual Output": "වැස්ස හිමින් හිමින් මේ පැත්තටත් එනවා වගේ නේ",
    "Status": "PASS",
    "What is covered by the test": "Daily language usage\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 8,
    "TC ID": "Pos_Fun_008",
    "Test Case Name": "Verify translation of tense variations (future)",
    "Input Type Length": "M",
    "Input": "api labana maasayeedhi hambavemu",
    "Expected Output": "අපි ලබන මාසයේදි හම්බවෙමු",
    "Actual Output": "අපි ලබන මාසයේදි හම්බවෙමු",
    "Status": "PASS",
    "What is covered by the test": "Daily language usage\r\nFuture tense\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 9,
    "TC ID": "Pos_Fun_009",
    "Test Case Name": "Verify translation of negation patterns",
    "Input Type Length": "M",
    "Input": "\"aa ehemadha? naehae! mQQ dhaenagena hitiyee naehae.\" ",
    "Expected Output": "\"ආ එහෙමද? නැහැ! මං දැනගෙන හිටියේ නැහැ.\" ",
    "Actual Output": "\"ආ එහෙමද? නැහැ! මං දැනගෙන හිටියේ නැහැ.\" ",
    "Status": "PASS",
    "What is covered by the test": "Punctuation / numbers\r\nNegation (negative form)\r\nm (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 10,
    "TC ID": "Pos_Fun_010",
    "Test Case Name": "Verify translation of singular usage",
    "Input Type Length": "M",
    "Input": "\"mama kammalkaarayek haetiyata jiivithee aluthin patan ganna poddakvath kaemathi vunee naee\"",
    "Expected Output": "\"මම කම්මල්කාරයෙක් හැටියට ජීවිතේ අලුතින් පටන් ගන්න පොඩ්ඩක්වත් කැමති වුනේ නෑ\"",
    "Actual Output": "\"මම කම්මල්කාරයෙක් හැටියට ජීවිතේ අලුතින් පටන් ගන්න පොඩ්ඩක්වත් කැමති වුනේ නෑ\"",
    "Status": "PASS",
    "What is covered by the test": "Response\r\nPronoun variation\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 11,
    "TC ID": "Pos_Fun_011",
    "Test Case Name": "Verify translation of request forms with varying degrees of politeness",
    "Input Type Length": "M",
    "Input": "\"mata samavenna! obata haeki ikmanin mata ee liyavilla labaa dhiya haeki dha?\"",
    "Expected Output": "\"මට සමවෙන්න! ඔබට හැකි ඉක්මනින් මට ඒ ලියවිල්ල ලබා දිය හැකි ද?\"",
    "Actual Output": "\"මට සමවෙන්න! ඔබට හැකි ඉක්මනින් මට ඒ ලියවිල්ල ලබා දිය හැකි ද?\"",
    "Status": "PASS",
    "What is covered by the test": "Request\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 12,
    "TC ID": "Pos_Fun_012",
    "Test Case Name": "Verify translation of English technical/brand terms embedded in Singlish",
    "Input Type Length": "M",
    "Input": "oyaa adha thiyena session ekata join venna dha inne? mata Microsoft teams link eka share karannako. Course Web eka mata access karanna baee ne.",
    "Expected Output": "ඔයා අද තියෙන session එකට join වෙන්න ද ඉන්නේ? මට Microsoft teams link එක share කරන්නකො. Course Web එක මට access කරන්න බෑ නේ.",
    "Actual Output": "ඔයා අද තියෙන session එකට join වෙන්න ද ඉන්නේ? මට Microsoft teams link එක share කරන්නකො. Course Web එක මට access කරන්න බෑ නේ.",
    "Status": "PASS",
    "What is covered by the test": "Mixed Singlish + English\r\nCompound sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 13,
    "TC ID": "Pos_Fun_013",
    "Test Case Name": "Verify translation of sentences containing  common English words ",
    "Input Type Length": "M",
    "Input": "Congratulations! maQQ dhaekkaa linkedin post eka oyaata promotion ekak laebunaa kiyalaa.",
    "Expected Output": "Congratulations! මං දැක්කා linkedin post එක ඔයාට promotion එකක් ලැබුනා කියලා.",
    "Actual Output": "Congratulations! මං දැක්කා linkedin post එක ඔයාට promotion එකක් ලැබුනා කියලා.",
    "Status": "PASS",
    "What is covered by the test": "Common english words\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 14,
    "TC ID": "Pos_Fun_014",
    "Test Case Name": "Verify translation of english abbreviations and short forms ",
    "Input Type Length": "M",
    "Input": "HR manager mata kivvaa mage reporting manager va CC karalaa mage request eka ewanna kiyalaa. CV ekayi NIC ekeyi copies uth attach karanna oonee ee email ekatama. ",
    "Expected Output": "HR manager මට කිව්වා mage reporting manager ව CC කරලා mage request එක එwඅන්න කියලා. CV එකයි NIC එකෙයි copies උත් attach කරන්න ඕනේ ඒ email එකටම. ",
    "Actual Output": "HR manager මට කිව්වා mage reporting manager ව CC කරලා mage request එක එwඅන්න කියලා. CV එකයි NIC එකෙයි copies උත් attach කරන්න ඕනේ ඒ email එකටම. ",
    "Status": "PASS",
    "What is covered by the test": "Mixed Singlish + English\r\nCompound sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 15,
    "TC ID": "Pos_Fun_015",
    "Test Case Name": "Verify translation of inputs containing punctuation marks",
    "Input Type Length": "M",
    "Input": "\"monavaa!! ohuta kisiseethma ayithiyak naee obata esee pavasanna. aeyi oba kisi dheyak pavasannee naethuva sitiyee??!\" ",
    "Expected Output": "\"මොනවා!! ඔහුට කිසිසේත්ම අයිතියක් නෑ ඔබට එසේ පවසන්න. ඇයි ඔබ කිසි දෙයක් පවසන්නේ නැතුව සිටියේ??!\" ",
    "Actual Output": "\"මොනවා!! ඔහුට කිසිසේත්ම අයිතියක් නෑ ඔබට එසේ පවසන්න. ඇයි ඔබ කිසි දෙයක් පවසන්නේ නැතුව සිටියේ??!\" ",
    "Status": "PASS",
    "What is covered by the test": "Punctuation\r\nComplex sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 16,
    "TC ID": "Pos_Fun_016",
    "Test Case Name": "Verify translation of multiple spaces, line breaks, and paragraph inputs",
    "Input Type Length": "M",
    "Input": "api heta udhenma   bas ekata     nagimu needha? \r\nethakota apita   kalin yanna puluvan office ekata",
    "Expected Output": "අපි හෙට උදෙන්ම   බස් එකට     නගිමු නේද? \r\nඑතකොට අපිට   කලින් යන්න පුලුවන් office එකට",
    "Actual Output": "අපි හෙට උදෙන්ම   බස් එකට     නගිමු නේද? \r\nඑතකොට අපිට   කලින් යන්න පුලුවන් office එකට",
    "Status": "PASS",
    "What is covered by the test": "Daily language usage\r\nCompound sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 17,
    "TC ID": "Pos_Fun_017",
    "Test Case Name": "Verify translation of Slang and colloquial phrasing",
    "Input Type Length": "M",
    "Input": "\"ayiyoo! mata amathaka vunaa eeka genna adha. kamak naedhdha maQQ heta genaavoth?\"",
    "Expected Output": "\"අයියෝ! මට අමතක වුනා ඒක ගෙන්න අද. කමක් නැද්ද මං හෙට ගෙනාවොත්?\"",
    "Actual Output": "\"අයියෝ! මට අමතක වුනා ඒක ගෙන්න අද. කමක් නැද්ද මං හෙට ගෙනාවොත්?\"",
    "Status": "PASS",
    "What is covered by the test": "Slang/ Informal language\r\nCompound sentence\r\nM (31-299 charactes)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 18,
    "TC ID": "Pos_Fun_018",
    "Test Case Name": "Verify translation of common english words ",
    "Input Type Length": "M",
    "Input": "oyaalaa group details dhaalaa register vunaadha?",
    "Expected Output": "ඔයාලා group details දාලා register වුනාද?",
    "Actual Output": "ඔයාලා group details දාලා register වුනාද?",
    "Status": "PASS",
    "What is covered by the test": "Names / places / common English words\r\nInterrogative (question)\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 19,
    "TC ID": "Pos_Fun_019",
    "Test Case Name": "Verify translation of simple sentence",
    "Input Type Length": "M",
    "Input": "oyaata mokakdha magen kerenna oonee? ",
    "Expected Output": "ඔයාට මොකක්ද මගෙන් කෙරෙන්න ඕනේ? ",
    "Actual Output": "ඔයාට මොකක්ද මගෙන් කෙරෙන්න ඕනේ? ",
    "Status": "PASS",
    "What is covered by the test": "Response\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 20,
    "TC ID": "Pos_Fun_020",
    "Test Case Name": "Verify translation of greeting",
    "Input Type Length": "M",
    "Input": "suba udhaeesanak veevaa oba saemata!",
    "Expected Output": "සුබ උදෑසනක් වේවා ඔබ සැමට!",
    "Actual Output": "සුබ උදෑසනක් වේවා ඔබ සැමට!",
    "Status": "PASS",
    "What is covered by the test": "Greeting\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 21,
    "TC ID": "Pos_Fun_021",
    "Test Case Name": "Verify translation  of slang/ informal language",
    "Input Type Length": "M",
    "Input": "loku loku scene meheth venavaa lu",
    "Expected Output": "ලොකු ලොකු scene මෙහෙත් වෙනවා ලු",
    "Actual Output": "ලොකු ලොකු scene මෙහෙත් වෙනවා ලු",
    "Status": "PASS",
    "What is covered by the test": "Daily language usage\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 22,
    "TC ID": "Pos_Fun_022",
    "Test Case Name": "Verify translation of english abbreviations",
    "Input Type Length": "M",
    "Input": "MERN stack kiyanne giya paara api ITP project ekata use karapu tech stack eka",
    "Expected Output": "MERN stack කියන්නෙ ගිය පාර අපි ITP project එකට use කරපු tech stack එක",
    "Actual Output": "MERN stack කියන්නෙ ගිය පාර අපි ITP project එකට use කරපු tech stack එක",
    "Status": "PASS",
    "What is covered by the test": "Mixed singlish + english\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 23,
    "TC ID": "Pos_Fun_023",
    "Test Case Name": "Verify translation of time formats",
    "Input Type Length": "M",
    "Input": "apee iskoolee 7.30 a.m. idhan 1.30 p.m. venakan thiyenavaa",
    "Expected Output": "අපේ ඉස්කෝලේ 7.30 a.m. ඉදන් 1.30 p.m. වෙනකන් තියෙනවා",
    "Actual Output": "අපේ ඉස්කෝලේ 7.30 a.m. ඉදන් 1.30 p.m. වෙනකන් තියෙනවා",
    "Status": "PASS",
    "What is covered by the test": "Response\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 24,
    "TC ID": "Pos_Fun_024",
    "Test Case Name": "Verify translation of units of measurements",
    "Input Type Length": "M",
    "Input": "mata paan piti 1kg dhenna puluvan dha? ",
    "Expected Output": "මට පාන් පිටි 1kg දෙන්න පුලුවන් ද? ",
    "Actual Output": "මට පාන් පිටි 1kg දෙන්න පුලුවන් ද? ",
    "Status": "PASS",
    "What is covered by the test": "Request\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 25,
    "TC ID": "Neg_Fun_001",
    "Test Case Name": "Verify command form\r\n",
    "Input Type Length": "M",
    "Input": "oyaa main building 7th floor ekata gihin LIC va hambavelaa new building ekee 2nd floor ekata ikmanatama enna. ",
    "Expected Output": "ඔයා main building 7th floor එකට ගිහින් LIC ව හම්බවෙලා new building එකේ 2nd floor එකට ඉක්මනටම එන්න.",
    "Actual Output": "ඔයා main building 7ත් floor එකට ගිහින් LIC ව හම්බවෙලා new building එකේ 2න්ඩ් floor එකට ඉක්මනටම එන්න.",
    "Status": "FAIL",
    "What is covered by the test": "Names / places / common English words\r\nImperative (command)\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 26,
    "TC ID": "Neg_Fun_002",
    "Test Case Name": "Verify translation of joined words",
    "Input Type Length": "M",
    "Input": "mama mee sem eketh kohomahari deans' list ekata select vena vaa",
    "Expected Output": "මම මේ sem එකෙත් කොහොමහරි deans' list එකට select වෙනවා",
    "Actual Output": "මම මේ සෙම් එකෙත් කොහොමහරි deans' list එකට select වෙනවා",
    "Status": "FAIL",
    "What is covered by the test": "Formatting (spaces / line breaks / paragraph)\r\nPronoun variation\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 27,
    "TC ID": "Neg_Fun_003",
    "Test Case Name": "Verify translation of currency",
    "Input Type Length": "M",
    "Input": "Bahraini Dinar kiyanne Bahrain ratee currency eka",
    "Expected Output": "Baharaini Dinar කියන්නෙ Bahrain රටේ currency එක",
    "Actual Output": "ඹහ්‍රෛනි Dinar කියන්නෙ Bahrain රටේ currency එක",
    "Status": "FAIL",
    "What is covered by the test": "Daily language usage\r\nSimple sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 28,
    "TC ID": "Neg_Fun_004",
    "Test Case Name": "Verify translation of Sinhala + English phrase",
    "Input Type Length": "M",
    "Input": "eyaava mata hambunee naee. maQQ eyaata kiyanna oonee \"I am sorry for everything\" kiyalaa",
    "Expected Output": "එයාව මට හම්බුනේ නෑ. මං එයාට කියන්න ඕනේ \"I am sorry for everything\" කියලා",
    "Actual Output": "එයාව මට හම්බුනේ නෑ. මං එයාට කියන්න ඕනේ \"ඉ am sorry for everything\" කියලා",
    "Status": "FAIL",
    "What is covered by the test": "Mixed Singlish + English\r\nPronoun variation\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 29,
    "TC ID": "Neg_Fun_005",
    "Test Case Name": "Verify translation of complete english phrase",
    "Input Type Length": "M",
    "Input": "I am really really sorry. What should I do? Never have I ever doubted you. Please forgive me.",
    "Expected Output": "I am really really sorry. What should I do? Never have I ever doubted you. Please forgive me.",
    "Actual Output": "ඉ am really really sorry. What should ඉ ඩො? Never have ඉ ever doubted you. Please forgive මෙ.",
    "Status": "FAIL",
    "What is covered by the test": "Common English words\r\nComplex sentence\r\nM (31-299 characters)\r\nAccuracy Validation"
  },
  {
    "__EMPTY": 30,
    "TC ID": "Neg_Fun_006",
    "Test Case Name": "Verify translation of phrases with missing spaces",
    "Input Type Length": "S",
    "Input": "oyaamataennakivveenaeenee  ",
    "Expected Output": "ඔයා මට එන්න කිව්වේ නෑනේ   ",
    "Actual Output": "ඔයාමටැන්නකිව්වේනෑනේ  ",
    "Status": "FAIL",
    "What is covered by the test": "Simple sentence\r\nResponse\r\nS ( ≤30 characters) \r\nRobustness Validation"
  },
  {
    "__EMPTY": 31,
    "TC ID": "Neg_Fun_007",
    "Test Case Name": "Verify translation  of slang/ informal language",
    "Input Type Length": "M",
    "Input": "Intern ekak set vunaa dha oyaata?  ",
    "Expected Output": "Intern එකක් set වුනා ද ඔයාට? ",
    "Actual Output": "Intern එකක් සෙට් වුනා ද ඔයාට? ",
    "Status": "FAIL",
    "What is covered by the test": "Word combination\r\nSimple sentence\r\nS ( ≤30 characters) \r\nRobustness Validation"
  },
  {
    "__EMPTY": 32,
    "TC ID": "Neg_Fun_008",
    "Test Case Name": "Verify translation of daily conversation_2",
    "Input Type Length": "M",
    "Input": "oyaage student id ekee copy ekak dhunnaa needha eyaalata?",
    "Expected Output": "ඔයාගෙ student id එකේ copy එකක් දුන්නා නේද එයාලට?",
    "Actual Output": "ඔයාගෙ student ඉඩ් එකේ copy එකක් දුන්නා නේද එයාලට?",
    "Status": "FAIL",
    "What is covered by the test": "Mixed Singlish + English\r\nSimple sentence\r\nS ( ≤30 characters) \r\nRobustness Validation"
  },
  {
    "__EMPTY": 33,
    "TC ID": "Neg_Fun_009",
    "Test Case Name": "Verify translation of english phrase with date",
    "Input Type Length": "S",
    "Input": "Her birthday is on 2003.08.20",
    "Expected Output": "Her birthday is on 2003.08.20",
    "Actual Output": "Her birthday ඉස් on 2003.08.20",
    "Status": "FAIL",
    "What is covered by the test": "Daily language usage\r\nPronoun variation\r\nS ( ≤30 characters) \r\nRobustness Validation"
  },
  {
    "__EMPTY": 34,
    "TC ID": "Neg_Fun_010",
    "Test Case Name": "Verify translation of english short form",
    "Input Type Length": "S",
    "Input": "Oyaage cgpa eka kiiyadha?",
    "Expected Output": "ඔයාගෙ gpa එක කීයද?",
    "Actual Output": "ඔයාගෙ cග්ප එක කීයද?",
    "Status": "FAIL",
    "What is covered by the test": "Common english words\r\nSimple sentence\r\nS ( ≤30 characters) \r\nRobustness Validation"
  }
];

module.exports = testData;